In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("Book1.csv")

In [8]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance
0,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25.0,Female,Marketing,NaN,Pune,2.0,Good
4,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,NaN,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31.0,Male,HR,67000.0,NaN,7.0,Excellent
7,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,NaN
8,1009,Karan,28.0,Male,NaN,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,NaN,Average
10,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,NaN,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24.0,Female,Sales,38000.0,Surat,2.0,NaN
14,1015,Deepak,27.0,Male,Marketing,47000.0,NaN,4.0,Very Good
15,1016,Komal,26.0,Female,IT,NaN,Agra,3.0,Excellent
16,1017,Sandeep,32.0,Male,HR,69000.0,Ranchi,NaN,Very Good
17,1018,Meena,28.0,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30.0,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23.0,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34.0,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27.0,Female,HR,46000.0,Ahmedabad,NaN,Good
22,1023,Imran,29.0,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,NaN,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31.0,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28.0,Female,IT,56000.0,NaN,4.0,Very Good
26,1027,Harsh,26.0,Male,NaN,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30.0,Female,Finance,68000.0,Mysuru,7.0,NaN
28,1029,Manish,24.0,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33.0,Female,IT,76000.0,Bhubaneswar,9.0,Excellent

In [9]:
df.isnull()

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,False,False,True
8,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,True,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,True
14,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,True,False,False,False
16,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False
22,False,False,False,False,False,False,False,False,False
23,False,False,True,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,True,False,False
26,False,False,False,False,True,False,False,False,False
27,False,False,False,False,False,False,False,False,True
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

ID             0
Name           0
Age            3
Gender         0
Department     2
Salary         2
City           3
Experience     3
Performance    3
dtype: int64

In [12]:
df.dropna()

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance
0,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good
4,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent
10,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good
17,1018,Meena,28.0,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30.0,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23.0,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34.0,Male,IT,82000.0,Bengaluru,11.0,Excellent
22,1023,Imran,29.0,Male,Finance,59000.0,Aligarh,5.0,Very Good
24,1025,Yash,31.0,Male,Marketing,64000.0,Gurugram,7.0,Excellent
28,1029,Manish,24.0,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33.0,Female,IT,76000.0,Bhubaneswar,9.0,Excellent

In [13]:
df.dropna(axis=1)

      ID     Name  Gender
0   1001     Aman    Male
1   1002    Priya  Female
2   1003    Rahul    Male
3   1004    Sneha  Female
4   1005    Arjun    Male
5   1006     Neha  Female
6   1007    Mohit    Male
7   1008   Simran  Female
8   1009    Karan    Male
9   1010    Pooja  Female
10  1011    Rohan    Male
11  1012   Anjali  Female
12  1013    Vivek    Male
13  1014    Nisha  Female
14  1015   Deepak    Male
15  1016    Komal  Female
16  1017  Sandeep    Male
17  1018    Meena  Female
18  1019     Ajay    Male
19  1020   Kavita  Female
20  1021    Rohit    Male
21  1022    Aisha  Female
22  1023    Imran    Male
23  1024   Sakshi  Female
24  1025     Yash    Male
25  1026    Tanya  Female
26  1027    Harsh    Male
27  1028     Ritu  Female
28  1029   Manish    Male
29  1030   Shreya  Female

In [14]:
df["Age"].fillna(df["Age"].mean())

0     23.000000
1     27.000000
2     30.000000
3     25.000000
4     29.000000
5     28.037037
6     31.000000
7     26.000000
8     28.000000
9     22.000000
10    35.000000
11    29.000000
12    28.037037
13    24.000000
14    27.000000
15    26.000000
16    32.000000
17    28.000000
18    30.000000
19    23.000000
20    34.000000
21    27.000000
22    29.000000
23    28.037037
24    31.000000
25    28.000000
26    26.000000
27    30.000000
28    24.000000
29    33.000000
Name: Age, dtype: float64

In [15]:
df.fillna(method="ffill")

C:\Users\Dell\AppData\Local\Temp\ipykernel_17916\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance
0,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25.0,Female,Marketing,62000.0,Pune,2.0,Good
4,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,29.0,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31.0,Male,HR,67000.0,Noida,7.0,Excellent
7,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,Excellent
8,1009,Karan,28.0,Male,Finance,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,4.0,Average
10,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,29.0,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24.0,Female,Sales,38000.0,Surat,2.0,Excellent
14,1015,Deepak,27.0,Male,Marketing,47000.0,Surat,4.0,Very Good
15,1016,Komal,26.0,Female,IT,47000.0,Agra,3.0,Excellent
16,1017,Sandeep,32.0,Male,HR,69000.0,Ranchi,3.0,Very Good
17,1018,Meena,28.0,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30.0,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23.0,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34.0,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27.0,Female,HR,46000.0,Ahmedabad,11.0,Good
22,1023,Imran,29.0,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,29.0,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31.0,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28.0,Female,IT,56000.0,Gurugram,4.0,Very Good
26,1027,Harsh,26.0,Male,IT,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30.0,Female,Finance,68000.0,Mysuru,7.0,Good
28,1029,Manish,24.0,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33.0,Female,IT,76000.0,Bhubaneswar,9.0,Excellent

In [16]:
import pandas as pd

In [17]:
df=pd.read_csv("Book2.csv")

In [18]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance
0,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25.0,Female,Marketing,NaN,Pune,2.0,Good
4,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,NaN,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31.0,Male,HR,67000.0,NaN,7.0,Excellent
7,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,NaN
8,1009,Karan,28.0,Male,NaN,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,NaN,Average
10,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,NaN,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24.0,Female,Sales,38000.0,Surat,2.0,NaN
14,1015,Deepak,27.0,Male,Marketing,47000.0,NaN,4.0,Very Good
15,1016,Komal,26.0,Female,IT,NaN,Agra,3.0,Excellent
16,1017,Sandeep,32.0,Male,HR,69000.0,Ranchi,NaN,Very Good
17,1018,Meena,28.0,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30.0,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23.0,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34.0,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27.0,Female,HR,46000.0,Ahmedabad,NaN,Good
22,1023,Imran,29.0,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,NaN,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31.0,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28.0,Female,IT,56000.0,NaN,4.0,Very Good
26,1027,Harsh,26.0,Male,NaN,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30.0,Female,Finance,68000.0,Mysuru,7.0,NaN
28,1029,Manish,24.0,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33.0,Female,IT,76000.0,Bhubaneswar,9.0,Excellent
30,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good
31,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent
32,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good
33,1004,Sneha,25.0,Female,Marketing,NaN,Pune,2.0,Good
34,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent
35,1006,Neha,NaN,Female,IT,39000.0,Noida,2.0,Good
36,1007,Mohit,31.0,Male,HR,67000.0,NaN,7.0,Excellent
37,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,NaN
38,1009,Karan,28.0,Male,NaN,53000.0,Chandigarh,4.0,Good
39,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,NaN,Average
40,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent
41,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good

In [20]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
dtype: bool

In [26]:
df.drop_duplicates()

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance
0,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25.0,Female,Marketing,NaN,Pune,2.0,Good
4,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,NaN,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31.0,Male,HR,67000.0,NaN,7.0,Excellent
7,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,NaN
8,1009,Karan,28.0,Male,NaN,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,NaN,Average
10,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,NaN,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24.0,Female,Sales,38000.0,Surat,2.0,NaN
14,1015,Deepak,27.0,Male,Marketing,47000.0,NaN,4.0,Very Good
15,1016,Komal,26.0,Female,IT,NaN,Agra,3.0,Excellent
16,1017,Sandeep,32.0,Male,HR,69000.0,Ranchi,NaN,Very Good
17,1018,Meena,28.0,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30.0,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23.0,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34.0,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27.0,Female,HR,46000.0,Ahmedabad,NaN,Good
22,1023,Imran,29.0,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,NaN,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31.0,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28.0,Female,IT,56000.0,NaN,4.0,Very Good
26,1027,Harsh,26.0,Male,NaN,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30.0,Female,Finance,68000.0,Mysuru,7.0,NaN
28,1029,Manish,24.0,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33.0,Female,IT,76000.0,Bhubaneswar,9.0,Excellent

In [27]:
df["Name"].str.lower()

0        aman
1       priya
2       rahul
3       sneha
4       arjun
5        neha
6       mohit
7      simran
8       karan
9       pooja
10      rohan
11     anjali
12      vivek
13      nisha
14     deepak
15      komal
16    sandeep
17      meena
18       ajay
19     kavita
20      rohit
21      aisha
22      imran
23     sakshi
24       yash
25      tanya
26      harsh
27       ritu
28     manish
29     shreya
30       aman
31      priya
32      rahul
33      sneha
34      arjun
35       neha
36      mohit
37     simran
38      karan
39      pooja
40      rohan
41     anjali
Name: Name, dtype: object

In [28]:
df["City"].str.contains("delhi", case=False)

0      True
1     False
2     False
3     False
4     False
5     False
6       NaN
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14      NaN
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25      NaN
26    False
27    False
28    False
29    False
30     True
31    False
32    False
33    False
34    False
35    False
36      NaN
37    False
38    False
39    False
40    False
41    False
Name: City, dtype: object

In [31]:
df2=df.dropna().copy()

In [33]:
df2["Age"]=df2["Age"].astype(int)

df2

In [35]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 41
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           20 non-null     int64
 1   Name         20 non-null     object
 2   Age          20 non-null     int64
 3   Gender       20 non-null     object
 4   Department   20 non-null     object
 5   Salary       20 non-null     float64
 6   City         20 non-null     object
 7   Experience   20 non-null     float64
 8   Performance  20 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.6+ KB

In [36]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")

In [37]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance,Age Group
0,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good,Adult
1,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent,Adult
2,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good,Adult
3,1004,Sneha,25.0,Female,Marketing,NaN,Pune,2.0,Good,Adult
4,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent,Adult
5,1006,Neha,NaN,Female,IT,39000.0,Noida,2.0,Good,Minor
6,1007,Mohit,31.0,Male,HR,67000.0,NaN,7.0,Excellent,Adult
7,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,NaN,Adult
8,1009,Karan,28.0,Male,NaN,53000.0,Chandigarh,4.0,Good,Adult
9,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,NaN,Average,Adult
10,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent,Adult
11,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good,Adult
12,1013,Vivek,NaN,Male,Finance,71000.0,Patna,8.0,Excellent,Minor
13,1014,Nisha,24.0,Female,Sales,38000.0,Surat,2.0,NaN,Adult
14,1015,Deepak,27.0,Male,Marketing,47000.0,NaN,4.0,Very Good,Adult
15,1016,Komal,26.0,Female,IT,NaN,Agra,3.0,Excellent,Adult
16,1017,Sandeep,32.0,Male,HR,69000.0,Ranchi,NaN,Very Good,Adult
17,1018,Meena,28.0,Female,Finance,58000.0,Varanasi,5.0,Good,Adult
18,1019,Ajay,30.0,Male,Sales,61000.0,Kochi,6.0,Excellent,Adult
19,1020,Kavita,23.0,Female,Marketing,35000.0,Dehradun,1.0,Average,Adult
20,1021,Rohit,34.0,Male,IT,82000.0,Bengaluru,11.0,Excellent,Adult
21,1022,Aisha,27.0,Female,HR,46000.0,Ahmedabad,NaN,Good,Adult
22,1023,Imran,29.0,Male,Finance,59000.0,Aligarh,5.0,Very Good,Adult
23,1024,Sakshi,NaN,Female,Sales,42000.0,Meerut,2.0,Good,Minor
24,1025,Yash,31.0,Male,Marketing,64000.0,Gurugram,7.0,Excellent,Adult
25,1026,Tanya,28.0,Female,IT,56000.0,NaN,4.0,Very Good,Adult
26,1027,Harsh,26.0,Male,NaN,43000.0,Jodhpur,3.0,Good,Adult
27,1028,Ritu,30.0,Female,Finance,68000.0,Mysuru,7.0,NaN,Adult
28,1029,Manish,24.0,Male,Sales,37000.0,Gwalior,2.0,Average,Adult
29,1030,Shreya,33.0,Female,IT,76000.0,Bhubaneswar,9.0,Excellent,Adult
30,1001,Aman,23.0,Male,HR,32000.0,Delhi,1.0,Good,Adult
31,1002,Priya,27.0,Female,IT,48000.0,Mumbai,3.0,Excellent,Adult
32,1003,Rahul,30.0,Male,Finance,62000.0,Lucknow,6.0,Very Good,Adult
33,1004,Sneha,25.0,Female,Marketing,NaN,Pune,2.0,Good,Adult
34,1005,Arjun,29.0,Male,Sales,55000.0,Jaipur,5.0,Excellent,Adult
35,1006,Neha,NaN,Female,IT,39000.0,Noida,2.0,Good,Minor
36,1007,Mohit,31.0,Male,HR,67000.0,NaN,7.0,Excellent,Adult
37,1008,Simran,26.0,Female,Finance,45000.0,Indore,3.0,NaN,Adult
38,1009,Karan,28.0,Male,NaN,53000.0,Chandigarh,4.0,Good,Adult
39,1010,Pooja,22.0,Female,Marketing,31000.0,Kanpur,NaN,Average,Adult
40,1011,Rohan,35.0,Male,IT,78000.0,Hyderabad,10.0,Excellent,Adult
41,1012,Anjali,29.0,Female,HR,49000.0,Chennai,5.0,Very Good,Adult

In [38]:
gender_map = {"M": "Male", "F": "Female"}
df["Gender"] = df["Gender"].map(gender_map)

In [40]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience,Performance,Age Group
0,1001,Aman,23.0,NaN,HR,32000.0,Delhi,1.0,Good,Adult
1,1002,Priya,27.0,NaN,IT,48000.0,Mumbai,3.0,Excellent,Adult
2,1003,Rahul,30.0,NaN,Finance,62000.0,Lucknow,6.0,Very Good,Adult
3,1004,Sneha,25.0,NaN,Marketing,NaN,Pune,2.0,Good,Adult
4,1005,Arjun,29.0,NaN,Sales,55000.0,Jaipur,5.0,Excellent,Adult
5,1006,Neha,NaN,NaN,IT,39000.0,Noida,2.0,Good,Minor
6,1007,Mohit,31.0,NaN,HR,67000.0,NaN,7.0,Excellent,Adult
7,1008,Simran,26.0,NaN,Finance,45000.0,Indore,3.0,NaN,Adult
8,1009,Karan,28.0,NaN,NaN,53000.0,Chandigarh,4.0,Good,Adult
9,1010,Pooja,22.0,NaN,Marketing,31000.0,Kanpur,NaN,Average,Adult
10,1011,Rohan,35.0,NaN,IT,78000.0,Hyderabad,10.0,Excellent,Adult
11,1012,Anjali,29.0,NaN,HR,49000.0,Chennai,5.0,Very Good,Adult
12,1013,Vivek,NaN,NaN,Finance,71000.0,Patna,8.0,Excellent,Minor
13,1014,Nisha,24.0,NaN,Sales,38000.0,Surat,2.0,NaN,Adult
14,1015,Deepak,27.0,NaN,Marketing,47000.0,NaN,4.0,Very Good,Adult
15,1016,Komal,26.0,NaN,IT,NaN,Agra,3.0,Excellent,Adult
16,1017,Sandeep,32.0,NaN,HR,69000.0,Ranchi,NaN,Very Good,Adult
17,1018,Meena,28.0,NaN,Finance,58000.0,Varanasi,5.0,Good,Adult
18,1019,Ajay,30.0,NaN,Sales,61000.0,Kochi,6.0,Excellent,Adult
19,1020,Kavita,23.0,NaN,Marketing,35000.0,Dehradun,1.0,Average,Adult
20,1021,Rohit,34.0,NaN,IT,82000.0,Bengaluru,11.0,Excellent,Adult
21,1022,Aisha,27.0,NaN,HR,46000.0,Ahmedabad,NaN,Good,Adult
22,1023,Imran,29.0,NaN,Finance,59000.0,Aligarh,5.0,Very Good,Adult
23,1024,Sakshi,NaN,NaN,Sales,42000.0,Meerut,2.0,Good,Minor
24,1025,Yash,31.0,NaN,Marketing,64000.0,Gurugram,7.0,Excellent,Adult
25,1026,Tanya,28.0,NaN,IT,56000.0,NaN,4.0,Very Good,Adult
26,1027,Harsh,26.0,NaN,NaN,43000.0,Jodhpur,3.0,Good,Adult
27,1028,Ritu,30.0,NaN,Finance,68000.0,Mysuru,7.0,NaN,Adult
28,1029,Manish,24.0,NaN,Sales,37000.0,Gwalior,2.0,Average,Adult
29,1030,Shreya,33.0,NaN,IT,76000.0,Bhubaneswar,9.0,Excellent,Adult
30,1001,Aman,23.0,NaN,HR,32000.0,Delhi,1.0,Good,Adult
31,1002,Priya,27.0,NaN,IT,48000.0,Mumbai,3.0,Excellent,Adult
32,1003,Rahul,30.0,NaN,Finance,62000.0,Lucknow,6.0,Very Good,Adult
33,1004,Sneha,25.0,NaN,Marketing,NaN,Pune,2.0,Good,Adult
34,1005,Arjun,29.0,NaN,Sales,55000.0,Jaipur,5.0,Excellent,Adult
35,1006,Neha,NaN,NaN,IT,39000.0,Noida,2.0,Good,Minor
36,1007,Mohit,31.0,NaN,HR,67000.0,NaN,7.0,Excellent,Adult
37,1008,Simran,26.0,NaN,Finance,45000.0,Indore,3.0,NaN,Adult
38,1009,Karan,28.0,NaN,NaN,53000.0,Chandigarh,4.0,Good,Adult
39,1010,Pooja,22.0,NaN,Marketing,31000.0,Kanpur,NaN,Average,Adult
40,1011,Rohan,35.0,NaN,IT,78000.0,Hyderabad,10.0,Excellent,Adult
41,1012,Anjali,29.0,NaN,HR,49000.0,Chennai,5.0,Very Good,Adult

In [41]:
df["City"].replace({"Del": "Delhi", "Mum": "Mumbai"})

0           Delhi
1          Mumbai
2         Lucknow
3            Pune
4          Jaipur
5           Noida
6             NaN
7          Indore
8      Chandigarh
9          Kanpur
10      Hyderabad
11        Chennai
12          Patna
13          Surat
14            NaN
15           Agra
16         Ranchi
17       Varanasi
18          Kochi
19       Dehradun
20      Bengaluru
21      Ahmedabad
22        Aligarh
23         Meerut
24       Gurugram
25            NaN
26        Jodhpur
27         Mysuru
28        Gwalior
29    Bhubaneswar
30          Delhi
31         Mumbai
32        Lucknow
33           Pune
34         Jaipur
35          Noida
36            NaN
37         Indore
38     Chandigarh
39         Kanpur
40      Hyderabad
41        Chennai
Name: City, dtype: object