In [1]:
import pandas as pd

In [1]:
df=pd.read_csv("data2.csv")

NameError: name 'pd' is not defined

In [3]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
0,1001,Aman,23,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25,Female,Marketing,41000.0,Pune,2.0,Good
4,1005,Arjun,29,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,24,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
7,1008,Simran,26,Female,Finance,45000.0,Indore,3.0,Very Good
8,1009,Karan,28,Male,Sales,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22,Female,Marketing,31000.0,Kanpur,1.0,Average
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24,Female,Sales,38000.0,Surat,2.0,Good
14,1015,Deepak,27,Male,Marketing,47000.0,Nagpur,4.0,Very Good
15,1016,Komal,26,Female,IT,52000.0,Agra,3.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
17,1018,Meena,28,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27,Female,HR,46000.0,Ahmedabad,3.0,Good
22,1023,Imran,29,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,25,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28,Female,IT,56000.0,Faridabad,4.0,Very Good
26,1027,Harsh,26,Male,HR,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent
28,1029,Manish,24,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.sort_values("Salary")

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
9,1010,Pooja,22,Female,Marketing,31000.0,Kanpur,1.0,Average
0,1001,Aman,23,Male,HR,32000.0,Delhi,1.0,Good
19,1020,Kavita,23,Female,Marketing,35000.0,Dehradun,1.0,Average
28,1029,Manish,24,Male,Sales,37000.0,Gwalior,2.0,Average
13,1014,Nisha,24,Female,Sales,38000.0,Surat,2.0,Good
5,1006,Neha,24,Female,IT,39000.0,Noida,2.0,Good
3,1004,Sneha,25,Female,Marketing,41000.0,Pune,2.0,Good
23,1024,Sakshi,25,Female,Sales,42000.0,Meerut,2.0,Good
26,1027,Harsh,26,Male,HR,43000.0,Jodhpur,3.0,Good
7,1008,Simran,26,Female,Finance,45000.0,Indore,3.0,Very Good
21,1022,Aisha,27,Female,HR,46000.0,Ahmedabad,3.0,Good
14,1015,Deepak,27,Male,Marketing,47000.0,Nagpur,4.0,Very Good
1,1002,Priya,27,Female,IT,48000.0,Mumbai,3.0,Excellent
11,1012,Anjali,29,Female,HR,49000.0,Chennai,5.0,Very Good
15,1016,Komal,26,Female,IT,52000.0,Agra,3.0,Excellent
8,1009,Karan,28,Male,Sales,53000.0,Chandigarh,4.0,Good
4,1005,Arjun,29,Male,Sales,55000.0,Jaipur,5.0,Excellent
25,1026,Tanya,28,Female,IT,56000.0,Faridabad,4.0,Very Good
17,1018,Meena,28,Female,Finance,58000.0,Varanasi,5.0,Good
22,1023,Imran,29,Male,Finance,59000.0,Aligarh,5.0,Very Good
18,1019,Ajay,30,Male,Sales,61000.0,Kochi,6.0,Excellent
2,1003,Rahul,30,Male,Finance,62000.0,Lucknow,6.0,Very Good
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.sort_values(["Salary","Age"]).copy()

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
9,1010,Pooja,22,Female,Marketing,31000.0,Kanpur,1.0,Average
0,1001,Aman,23,Male,HR,32000.0,Delhi,1.0,Good
19,1020,Kavita,23,Female,Marketing,35000.0,Dehradun,1.0,Average
28,1029,Manish,24,Male,Sales,37000.0,Gwalior,2.0,Average
13,1014,Nisha,24,Female,Sales,38000.0,Surat,2.0,Good
5,1006,Neha,24,Female,IT,39000.0,Noida,2.0,Good
3,1004,Sneha,25,Female,Marketing,41000.0,Pune,2.0,Good
23,1024,Sakshi,25,Female,Sales,42000.0,Meerut,2.0,Good
26,1027,Harsh,26,Male,HR,43000.0,Jodhpur,3.0,Good
7,1008,Simran,26,Female,Finance,45000.0,Indore,3.0,Very Good
21,1022,Aisha,27,Female,HR,46000.0,Ahmedabad,3.0,Good
14,1015,Deepak,27,Male,Marketing,47000.0,Nagpur,4.0,Very Good
1,1002,Priya,27,Female,IT,48000.0,Mumbai,3.0,Excellent
11,1012,Anjali,29,Female,HR,49000.0,Chennai,5.0,Very Good
15,1016,Komal,26,Female,IT,52000.0,Agra,3.0,Excellent
8,1009,Karan,28,Male,Sales,53000.0,Chandigarh,4.0,Good
4,1005,Arjun,29,Male,Sales,55000.0,Jaipur,5.0,Excellent
25,1026,Tanya,28,Female,IT,56000.0,Faridabad,4.0,Very Good
17,1018,Meena,28,Female,Finance,58000.0,Varanasi,5.0,Good
22,1023,Imran,29,Male,Finance,59000.0,Aligarh,5.0,Very Good
18,1019,Ajay,30,Male,Sales,61000.0,Kochi,6.0,Excellent
2,1003,Rahul,30,Male,Finance,62000.0,Lucknow,6.0,Very Good
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.reset_index(drop=True,inplace=True)

In [10]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
0,1001,Aman,23,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25,Female,Marketing,41000.0,Pune,2.0,Good
4,1005,Arjun,29,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,24,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
7,1008,Simran,26,Female,Finance,45000.0,Indore,3.0,Very Good
8,1009,Karan,28,Male,Sales,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22,Female,Marketing,31000.0,Kanpur,1.0,Average
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24,Female,Sales,38000.0,Surat,2.0,Good
14,1015,Deepak,27,Male,Marketing,47000.0,Nagpur,4.0,Very Good
15,1016,Komal,26,Female,IT,52000.0,Agra,3.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
17,1018,Meena,28,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27,Female,HR,46000.0,Ahmedabad,3.0,Good
22,1023,Imran,29,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,25,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28,Female,IT,56000.0,Faridabad,4.0,Very Good
26,1027,Harsh,26,Male,HR,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent
28,1029,Manish,24,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df["Rank"] = df["Experience (Years)"].rank(method="dense")

In [12]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance,Rank
0,1001,Aman,23,Male,HR,32000.0,Delhi,1.0,Good,2.0
1,1002,Priya,27,Female,IT,48000.0,Mumbai,3.0,Excellent,11.0
2,1003,Rahul,30,Male,Finance,62000.0,Lucknow,6.0,Very Good,21.5
3,1004,Sneha,25,Female,Marketing,41000.0,Pune,2.0,Good,6.0
4,1005,Arjun,29,Male,Sales,55000.0,Jaipur,5.0,Excellent,18.5
5,1006,Neha,24,Female,IT,39000.0,Noida,2.0,Good,6.0
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent,24.0
7,1008,Simran,26,Female,Finance,45000.0,Indore,3.0,Very Good,11.0
8,1009,Karan,28,Male,Sales,53000.0,Chandigarh,4.0,Good,15.0
9,1010,Pooja,22,Female,Marketing,31000.0,Kanpur,1.0,Average,2.0
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent,28.0
11,1012,Anjali,29,Female,HR,49000.0,Chennai,5.0,Very Good,18.5
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent,26.0
13,1014,Nisha,24,Female,Sales,38000.0,Surat,2.0,Good,6.0
14,1015,Deepak,27,Male,Marketing,47000.0,Nagpur,4.0,Very Good,15.0
15,1016,Komal,26,Female,IT,52000.0,Agra,3.0,Excellent,11.0
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good,27.0
17,1018,Meena,28,Female,Finance,58000.0,Varanasi,5.0,Good,18.5
18,1019,Ajay,30,Male,Sales,61000.0,Kochi,6.0,Excellent,21.5
19,1020,Kavita,23,Female,Marketing,35000.0,Dehradun,1.0,Average,2.0
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent,29.0
21,1022,Aisha,27,Female,HR,46000.0,Ahmedabad,3.0,Good,11.0
22,1023,Imran,29,Male,Finance,59000.0,Aligarh,5.0,Very Good,18.5
23,1024,Sakshi,25,Female,Sales,42000.0,Meerut,2.0,Good,6.0
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent,24.0
25,1026,Tanya,28,Female,IT,56000.0,Faridabad,4.0,Very Good,15.0
26,1027,Harsh,26,Male,HR,43000.0,Jodhpur,3.0,Good,11.0
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent,24.0
28,1029,Manish,24,Male,Sales,37000.0,Gwalior,2.0,Average,6.0
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN