In [2]:
import pandas as pd

In [3]:
data=[["alice",5],["stg",4],["shob",7],["nobe",3]]

In [4]:
pd.DataFrame(data,columns=["name","marks"])

    name  marks
0  alice      5
1    stg      4
2   shob      7
3   nobe      3

In [5]:
data={"a":[1,2,3,4],"b":[3,4,5,6]}

In [6]:
data

{'a': [1, 2, 3, 4], 'b': [3, 4, 5, 6]}

In [7]:
df=pd.DataFrame(data)

In [8]:
df

   a  b
0  1  3
1  2  4
2  3  5
3  4  6

In [9]:
import numpy as np

In [10]:
arr=np.array([[1,2],[3,4]])

In [11]:
df=pd.DataFrame(arr,columns=["A","B"])

In [12]:
df

   A  B
0  1  2
1  3  4

In [17]:
df=pd.read_excel("data.xlsx")

In [18]:
df

    name school  marks
0  najxd    ser     12
1   alex    ser     32
2    vcb   sers     43
3   cbfh   ftgd     22
4    dfd  tresd     44
5   dffg    fty     32
6    fgg     cg     13

In [19]:
df=pd.read_csv("data.csv")

In [20]:
df

    name school  marks
0  najxd    ser     12
1   alex    ser     32
2    vcb   sers     43
3   cbfh   ftgd     22
4    dfd  tresd     44
5   dffg    fty     32
6    fgg     cg     13

In [21]:
df=pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")

In [22]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [24]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [26]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [28]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [29]:
df.shape

(150, 5)

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data2.csv")

In [3]:
df

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
0,1001,Aman,23,Male,HR,32000.0,Delhi,1.0,Good
1,1002,Priya,27,Female,IT,48000.0,Mumbai,3.0,Excellent
2,1003,Rahul,30,Male,Finance,62000.0,Lucknow,6.0,Very Good
3,1004,Sneha,25,Female,Marketing,41000.0,Pune,2.0,Good
4,1005,Arjun,29,Male,Sales,55000.0,Jaipur,5.0,Excellent
5,1006,Neha,24,Female,IT,39000.0,Noida,2.0,Good
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
7,1008,Simran,26,Female,Finance,45000.0,Indore,3.0,Very Good
8,1009,Karan,28,Male,Sales,53000.0,Chandigarh,4.0,Good
9,1010,Pooja,22,Female,Marketing,31000.0,Kanpur,1.0,Average
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
11,1012,Anjali,29,Female,HR,49000.0,Chennai,5.0,Very Good
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
13,1014,Nisha,24,Female,Sales,38000.0,Surat,2.0,Good
14,1015,Deepak,27,Male,Marketing,47000.0,Nagpur,4.0,Very Good
15,1016,Komal,26,Female,IT,52000.0,Agra,3.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
17,1018,Meena,28,Female,Finance,58000.0,Varanasi,5.0,Good
18,1019,Ajay,30,Male,Sales,61000.0,Kochi,6.0,Excellent
19,1020,Kavita,23,Female,Marketing,35000.0,Dehradun,1.0,Average
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
21,1022,Aisha,27,Female,HR,46000.0,Ahmedabad,3.0,Good
22,1023,Imran,29,Male,Finance,59000.0,Aligarh,5.0,Very Good
23,1024,Sakshi,25,Female,Sales,42000.0,Meerut,2.0,Good
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
25,1026,Tanya,28,Female,IT,56000.0,Faridabad,4.0,Very Good
26,1027,Harsh,26,Male,HR,43000.0,Jodhpur,3.0,Good
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent
28,1029,Manish,24,Male,Sales,37000.0,Gwalior,2.0,Average
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['Name']

0        Aman
1       Priya
2       Rahul
3       Sneha
4       Arjun
5        Neha
6       Mohit
7      Simran
8       Karan
9       Pooja
10      Rohan
11     Anjali
12      Vivek
13      Nisha
14     Deepak
15      Komal
16    Sandeep
17      Meena
18       Ajay
19     Kavita
20      Rohit
21      Aisha
22      Imran
23     Sakshi
24       Yash
25      Tanya
26      Harsh
27       Ritu
28     Manish
29     Shreya
Name: Name, dtype: object

In [5]:
df[['Name','Department']]

       Name Department
0      Aman         HR
1     Priya         IT
2     Rahul    Finance
3     Sneha  Marketing
4     Arjun      Sales
5      Neha         IT
6     Mohit         HR
7    Simran    Finance
8     Karan      Sales
9     Pooja  Marketing
10    Rohan         IT
11   Anjali         HR
12    Vivek    Finance
13    Nisha      Sales
14   Deepak  Marketing
15    Komal         IT
16  Sandeep         HR
17    Meena    Finance
18     Ajay      Sales
19   Kavita  Marketing
20    Rohit         IT
21    Aisha         HR
22    Imran    Finance
23   Sakshi      Sales
24     Yash  Marketing
25    Tanya         IT
26    Harsh         HR
27     Ritu    Finance
28   Manish      Sales
29   Shreya        NaN

In [6]:
df.loc[1]

ID                         1002
Name                      Priya
Age                          27
Gender                   Female
Department                   IT
Salary                  48000.0
City                     Mumbai
Experience (Years)          3.0
Performance           Excellent
Name: 1, dtype: object

In [7]:
df.iloc[1]

ID                         1002
Name                      Priya
Age                          27
Gender                   Female
Department                   IT
Salary                  48000.0
City                     Mumbai
Experience (Years)          3.0
Performance           Excellent
Name: 1, dtype: object

In [8]:
df.loc[7,'Name']

'Simran'

In [11]:
df.loc[0:5,['Name','Department']]

    Name Department
0   Aman         HR
1  Priya         IT
2  Rahul    Finance
3  Sneha  Marketing
4  Arjun      Sales
5   Neha         IT

In [12]:
df.at[0,'Name']

'Aman'

In [13]:
df[df['Experience (Years)']>6.0]

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
27,1028,Ritu,30,Female,Finance,68000.0,Mysuru,7.0,Excellent

In [17]:
df[(df['Experience (Years)']>6.0)&(df['Age']>32)]

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent

In [19]:
df.query("Age>30")

,ID,Name,Age,Gender,Department,Salary,City,Experience (Years),Performance
6,1007,Mohit,31,Male,HR,67000.0,Bhopal,7.0,Excellent
10,1011,Rohan,35,Male,IT,78000.0,Hyderabad,10.0,Excellent
12,1013,Vivek,33,Male,Finance,71000.0,Patna,8.0,Excellent
16,1017,Sandeep,32,Male,HR,69000.0,Ranchi,9.0,Very Good
20,1021,Rohit,34,Male,IT,82000.0,Bengaluru,11.0,Excellent
24,1025,Yash,31,Male,Marketing,64000.0,Gurugram,7.0,Excellent
29,1030,Shreya,33,NaN,NaN,NaN,NaN,NaN,NaN